services:
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerConfigurationValidatorInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Validator\PsrLoggerConfigurationValidator
    public: false
  OxidEsales\EshopCommunity\Internal\Logger\Validator\Configuration\MonologConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'OXID Logger'
      $context: '@OxidEsales\EshopCommunity\Internal\Utility\ContextInterface'
    public: false
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Factory\MonologLoggerFactory
    autowire: true
    public: false
  Monolog\Logger:
    class: Monolog\Logger
    factory: 'OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerFactoryInterface:create'
    public: false
  Psr\Log\LoggerInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Wrapper\LoggerWrapper
    arguments:
      $logger: '@Monolog\Logger'
    public: true
